name: TF Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to destroy the infrastructure and avoid unnecessary charges"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  destroy:
    name: Destroy infrastructure
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init -input=false -reconfigure -backend-config="bucket=${{ vars.TERRAFORM_BUCKET_NAME }}" -backend-config="key=cloudsec/terraform.tfstate" -backend-config="region=${{ vars.AWS_REGION }}" -backend-config="encrypt=true"

      - name: Terraform destroy
        run: terraform destroy -auto-approve